global_frame: map
robot_base_frame: base_footprint
rolling_window: true
update_frequency: 10.0
publish_frequency: 10.0
static_map: false
always_send_full_costmap: false

width: 10.0
height: 10.0
resolution: 0.05
transform_tolerance: 0.5

plugins:
  #- {name: static,                    type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}