planner_frequency: 10.0
planner_patience: 5.0

controller_frequency: 1.0
controller_patience: 15.0

# Our carlike robot is not able to rotate in place
clearing_rotation_allowed: false

GlobalPlanner:
  use_dijkstra: true
  use_grid_path: false
  allow_unknown: false

path_planner:
  use_dijkstra: true
  use_grid_path: false
  allow_unknown: false
  cost_factor: 0.8

NavfnROS:
  allow_unknown: false

sbpl_planner:
  environment_type: XYThetaLattice
  planner_type: ARAPlanner
  allocated_time: 5.0
  initial_epsilon: 3.0
  forward_search: false
  nominalvel_mpersecs: 3.0


#TrajectoryPlannerROS:
#  sim_time: 10.0
#  dwa: true

#DWAPlannerROS:
##
##  acc_lim_th: 0.1
##  acc_lim_x: 0.5
##  acc_lim_y: 0.0
##
##  max_vel_x: 0.5
##  min_vel_x: 0.0
##
##  max_vel_y: 0.0
##  min_vel_y: 0.0
##
##  max_trans_vel: 0.5
##  min_trans_vel: 0.1
##  max_rot_vel: 0.2
##  min_rot_vel: 0.0
##
#  sim_time: 8.5
#
#  sim_granularity: 0.025
#
#  goal_distance_bias: 30.0
#  path_distance_bias: 20.0
#  occdist_scale: 0.01
#  forward_point_distance: 0.5
#  stop_time_buffer: 0.2
#  #######
#  scaling_speed: 0.5
#  #######
#  max_scaling_factor: 0.2
#  oscillation_reset_dist: 0.05
#
#  #
#  vx_samples: 20
#  vy_samples: 0
#  vtheta_samples: 10
#
#  rot_stopped_vel: 0.01
#  trans_stopped_vel: 0.01
#  #
#  xy_goal_tolerance: 0.2
#  yaw_goal_tolerance: 0.1
#  latch_xy_goal_tolerance: true