config:
  max_speed: &max_speed 2.5
  stable_speed: &stable_speed 2.5
  low_speed: &low_speed 2.5

  hard_cross: &hard_cross 2.5

pd_controller:
  stages:
    - stage: 0 # [first straight, straight after back-120]
      desire_velocity: *max_speed
      error_distance: 1.4
      pid_p: 0.6
      _exit:
        _distance: 2.0
        desire_velocity: *hard_cross
        pid_p: 0.8

    - stage: 1 # first cross
      # desire_velocity: 2.0
      error_distance: 1.2

#    - stage: 2
#      error_distance: 1.2

    - stage: 3 # [second straight, straight after u-turn, final straight]
      desire_velocity: *max_speed
      error_distance: 1.4
      _enter:
        _distance: 2.0
        error_distance: 1.3
        desire_velocity: *hard_cross

    - stage: 6 # [enter u, u1, u2]
      desire_velocity: 2.2

    - stage: 9
      error_distance: 1.4
      desire_velocity: *max_speed
#      _enter:
#        _distance: 2.0
#        error_distance: 0.5
#        desire_velocity: *max_speed

    - stage: 10
      error_distance: 1.4
      _exit:
        _distance: 0.8
        error_distance: 1.2

    - stage: 11
      error_distance: 1.4
      _enter:
        _distance: 0.8
        error_distance: 1.2

    - stage: 12
      error_distance: 1.4
      _exit:
        _distance: 2.0
        desire_velocity: 2.0


    - stage: 13 # second cross
      error_distance: 1.2

#    - stage: 14
#      error_distance: 1.2

    - stage: 15
      desire_velocity: *max_speed
      error_distance: 1.4
      _enter:
        _distance: 1.0
        error_distance: 1.3
        desire_velocity: 2.0

